export const FETCH_INITIAL_POSTS_REQUEST = "FETCH_INITIAL_POSTS_REQUEST";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const LOAD_MORE_REQUEST = "LOAD_MORE_REQUEST";
